### ISSUE TITLE
Support source tracking

### ISSUE THREAD

**Issue by FreshAlacrity** [FreshAlacrity/project-navigator#20]
- [ ] sort out how and when to have sources inherit from dependencies
- [x] decide if this should be folded into shoutout system
   - [ ] add support for that
      - [ ] figure out formatting/data structure for spreadsheet
      - [ ] figure out formatting/markdown structure for readme docs
